### ISSUE TITLE
[bug]: config window close buttons dont work on 0.3.1 and up

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/filebrowser-startos#27]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.5

### Browser

Firefox

### Browser Version

104.0b4

### Current Behavior

When opening the config options modal - X on the top right and close button on the bottom right are non-responsive.

### Expected Behavior

X button and close/save button should close the modal. 

### Steps to Reproduce

open config page.

**Comment by MattDHill** [comment]
There is likely an error in the console
